name: IDX Stock Screener - Rising Three Method

on:
  schedule:
    - cron: "0 4 * * 1-5"
    - cron: "0 8 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rising Three Method Screener
        run: |
          python main.py --strategy rising_three
          python main.py --strategy before_rising_three_method_with_volume
